constants:
  TARGET_PATH: $$CONFIG_PATH$$/$$$TARGET_NAME$$$
  LIBRARY_PATH: $$CONFIG_PATH$$/../
  WORK_DIR: $$$WORK_DIR$$$/work/$$$TARGET_NAME$$$
  PERSIST_DIR: $$$WORK_DIR$$$/persist/$$$TARGET_NAME$$$
  LIB_NAME: libtinyaes
---

general:
  logger:
    log-level: warning
    file: $$WORK_DIR$$/log.txt
  monitor:
    enable: true
    sample-rate: 50
   
testcase:
  module: random
  module-options:
    length: 16
    amount: 10
    output-directory: $$$TESTCASE_DIRECTORY$$$

trace:
  module: pin
  module-options:
    output-directory: $$WORK_DIR$$/traces
    pin-tool-path: $$$PINTOOL$$$
    pin-path: $$$PIN_PATH$$$/pin
    wrapper-path: $$TARGET_PATH$$
    environment:
      LD_LIBRARY_PATH: $$LIBRARY_PATH$$
    images:
      - $$$TARGET_NAME$$$
      - $$LIB_NAME$$.so
  options:
    input-buffer-size: 4
    
preprocess:
  module: pin
  module-options:
    output-directory: $$WORK_DIR$$/traces
    store-traces: true
    keep-raw-traces: false
  options:
    input-buffer-size: 2
    max-parallel-threads: 4
  
analysis:
  modules:
    - module: control-flow-leakage
      module-options:
        output-directory: $$PERSIST_DIR$$/control-flow-leakage
        map-files:
          - $$TARGET_PATH$$.map
          - $$LIB_NAME$$.map
        dump-call-tree: false
        include-testcases-in-call-stacks: false
    - module: call-stack-memory-access-trace-leakage
      module-options:
        output-directory: $$PERSIST_DIR$$/call-stack-memory-access-trace-leakage
        output-format: csv
        map-files:
          - $$TARGET_PATH$$.map
          - $$LIB_NAME$$.map
        dump-call-tree: false

  options:
    input-buffer-size: 1
    max-parallel-threads: 1